"""
AEVE 2.0 — StyleManifest builder.

Phase 0: deterministic, no LLM calls. Builds a StyleManifest based on inputs
(difficulty, palette preference, font availability) and writes two artifacts:

  1. output/style_manifest.json  — canonical JSON spec
  2. output/_style.py            — generated Python module that the Animator
                                    imports via `from output._style import *`

Every Director / Narrator / Animator prompt receives the JSON spec verbatim;
every generated Manim scene imports the Python constants. This guarantees a
single source of truth for palette, font, and layout coordinates.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Final

from pipeline.schemas import (
    Difficulty,
    FontFamily,
    LayoutZoneName,
    StyleManifest,
    TransitionKind,
)

# ---------------------------------------------------------------------------
# Default palettes — keyed by name; user can override via build_style_manifest
# ---------------------------------------------------------------------------

PALETTES: Final[dict[str, dict[str, str]]] = {
    "blue_yellow_dark": {
        "bg": "#0B1020",
        "primary": "#E8EEF7",
        "accent": "#FFD166",
        "muted": "#7A8AA8",
        "success": "#4ADE80",
        "warn": "#F87171",
    },
    "monochrome": {
        "bg": "#000000",
        "primary": "#FFFFFF",
        "accent": "#A0A0A0",
        "muted": "#606060",
        "success": "#FFFFFF",
        "warn": "#FFFFFF",
    },
    "warm": {
        "bg": "#1A0F0A",
        "primary": "#FBF1E3",
        "accent": "#F4A261",
        "muted": "#9C7C5B",
        "success": "#90B77D",
        "warn": "#E63946",
    },
}

# Six layout zones, expressed as (x, y) Manim coordinates.
# Manim frame is roughly 14.22 wide × 8 tall (default 16:9 at 8 units high).
LAYOUT_ZONES: Final[dict[LayoutZoneName, tuple[float, float]]] = {
    "title": (0.0, 3.2),
    "main": (0.0, 0.4),
    "caption": (0.0, -3.0),
    "left_rail": (-4.8, 0.0),
    "right_rail": (4.8, 0.0),
    "footer": (0.0, -3.6),
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_style_manifest(
    *,
    difficulty: Difficulty = "intermediate",
    palette_name: str = "blue_yellow_dark",
    font: FontFamily | None = None,
) -> StyleManifest:
    """Construct a StyleManifest deterministically.

    No LLM, no I/O. Pure function of the named arguments.
    """
    if palette_name not in PALETTES:
        raise ValueError(
            f"unknown palette {palette_name!r}; available: {sorted(PALETTES)}"
        )
    palette = dict(PALETTES[palette_name])

    chosen_font: FontFamily = font or _font_for_difficulty(difficulty)
    base_font_size = _base_font_size_for_difficulty(difficulty)
    transition: TransitionKind = "ReplacementTransform" if difficulty == "advanced" else "FadeOut"

    return StyleManifest(
        palette=palette,  # type: ignore[arg-type]
        font=chosen_font,
        base_font_size=base_font_size,
        frame_margin=0.5,
        transition=transition,
        layout_zones=LAYOUT_ZONES,
    )


def write_style_artifacts(manifest: StyleManifest, output_dir: Path) -> tuple[Path, Path]:
    """Write style_manifest.json + _style.py to output_dir.

    Returns (json_path, py_path).
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    json_path = output_dir / "style_manifest.json"
    py_path = output_dir / "_style.py"

    json_path.write_text(
        manifest.model_dump_json(indent=2),
        encoding="utf-8",
    )
    py_path.write_text(_render_style_module(manifest), encoding="utf-8")

    return json_path, py_path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _font_for_difficulty(difficulty: Difficulty) -> FontFamily:
    if difficulty == "advanced":
        return "Latin Modern Roman"
    return "Inter"


def _base_font_size_for_difficulty(difficulty: Difficulty) -> int:
    return {"intro": 40, "intermediate": 36, "advanced": 32}[difficulty]


def _render_style_module(manifest: StyleManifest) -> str:
    """Generate the importable Python constants module."""
    palette = manifest.palette
    zones = manifest.layout_zones

    lines: list[str] = [
        '"""',
        "AEVE 2.0 — generated style constants.",
        "",
        "DO NOT EDIT BY HAND. Regenerated by pipeline/style.py on every run.",
        "Every Animator-emitted Manim scene imports from this module.",
        '"""',
        "",
        "from manim import ORIGIN, UP, DOWN, LEFT, RIGHT  # noqa: F401",
        "",
        "# --- Palette --------------------------------------------------------",
        f'BG       = "{palette["bg"]}"',
        f'PRIMARY  = "{palette["primary"]}"',
        f'ACCENT   = "{palette["accent"]}"',
        f'MUTED    = "{palette["muted"]}"',
        f'SUCCESS  = "{palette["success"]}"',
        f'WARN     = "{palette["warn"]}"',
        "",
        "# --- Typography ----------------------------------------------------",
        f'FONT             = "{manifest.font}"',
        f"BASE_FONT_SIZE   = {manifest.base_font_size}",
        f"FRAME_MARGIN     = {manifest.frame_margin}",
        f'TRANSITION       = "{manifest.transition}"',
        "",
        "# --- Layout zones (Manim coordinates) ------------------------------",
    ]
    for name, (x, y) in zones.items():
        const_name = f"{name.upper()}_POS"
        lines.append(f"{const_name:<14} = ({x:.4f}, {y:.4f}, 0.0)")

    lines += [
        "",
        "LAYOUT_ZONES = {",
        *[
            f'    "{name}": ({x:.4f}, {y:.4f}, 0.0),'
            for name, (x, y) in zones.items()
        ],
        "}",
        "",
        "__all__ = [",
        '    "BG", "PRIMARY", "ACCENT", "MUTED", "SUCCESS", "WARN",',
        '    "FONT", "BASE_FONT_SIZE", "FRAME_MARGIN", "TRANSITION",',
        *[f'    "{name.upper()}_POS",' for name in zones],
        '    "LAYOUT_ZONES",',
        "]",
        "",
    ]
    return "\n".join(lines)


def manifest_to_prompt_block(manifest: StyleManifest) -> str:
    """Return a compact JSON block suitable for inlining into LLM prompts."""
    return json.dumps(manifest.model_dump(), indent=2, sort_keys=True)


__all__ = [
    "PALETTES",
    "LAYOUT_ZONES",
    "build_style_manifest",
    "write_style_artifacts",
    "manifest_to_prompt_block",
]
